// Generated by the Crawlora platform client generator. Do not edit.
export const operations = {
  "reddit-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-comments",
    "method": "GET",
    "path": "/reddit/comments/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "confidence",
          "top",
          "new",
          "controversial",
          "old",
          "qa"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "depth",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "include_metrics",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-domain-posts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-domain-posts",
    "method": "GET",
    "path": "/reddit/domain/{domain}/posts",
    "pathParams": [
      "domain"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "hot",
          "new",
          "top",
          "rising"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-leads": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-leads",
    "method": "GET",
    "path": "/reddit/leads",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "subreddit",
        "type": "string"
      },
      {
        "enum": [
          "relevance",
          "hot",
          "new",
          "top",
          "comments"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "min_score",
        "type": "integer"
      },
      {
        "enum": [
          "auto",
          "heuristic",
          "llm"
        ],
        "in": "query",
        "name": "classifier",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-post": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-post",
    "method": "GET",
    "path": "/reddit/post/{id}",
    "pathParams": [
      "id"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "include_metrics",
        "type": "boolean"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-search": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-search",
    "method": "GET",
    "path": "/reddit/search",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "q",
        "required": true,
        "type": "string"
      },
      {
        "in": "query",
        "name": "subreddit",
        "type": "string"
      },
      {
        "enum": [
          "relevance",
          "hot",
          "new",
          "top",
          "comments"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-subreddit-about": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-subreddit-about",
    "method": "GET",
    "path": "/reddit/subreddit/{subreddit}/about",
    "pathParams": [
      "subreddit"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-subreddit-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-subreddit-comments",
    "method": "GET",
    "path": "/reddit/subreddit/{subreddit}/comments",
    "pathParams": [
      "subreddit"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-subreddit-posts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-subreddit-posts",
    "method": "GET",
    "path": "/reddit/subreddit/{subreddit}/posts",
    "pathParams": [
      "subreddit"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "hot",
          "new",
          "top",
          "rising"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-subreddits-posts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-subreddits-posts",
    "method": "GET",
    "path": "/reddit/subreddits/posts",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "subreddits",
        "required": true,
        "type": "string"
      },
      {
        "enum": [
          "hot",
          "new",
          "top",
          "rising"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-trends": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-trends",
    "method": "GET",
    "path": "/reddit/trends",
    "pathParams": [],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "enum": [
          "hot",
          "new",
          "rising",
          "top"
        ],
        "in": "query",
        "name": "sort",
        "type": "string"
      },
      {
        "enum": [
          "hour",
          "day",
          "week",
          "month",
          "year",
          "all"
        ],
        "in": "query",
        "name": "time",
        "type": "string"
      },
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-user-comments": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-user-comments",
    "method": "GET",
    "path": "/reddit/user/{username}/comments",
    "pathParams": [
      "username"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  },
  "reddit-user-posts": {
    "bodyParam": null,
    "bodyRequired": false,
    "consumes": [
      "application/json"
    ],
    "formParams": [],
    "id": "reddit-user-posts",
    "method": "GET",
    "path": "/reddit/user/{username}/posts",
    "pathParams": [
      "username"
    ],
    "produces": [
      "application/json"
    ],
    "queryParams": [
      {
        "in": "query",
        "name": "limit",
        "type": "integer"
      },
      {
        "in": "query",
        "name": "after",
        "type": "string"
      }
    ],
    "security": [
      "ApiKeyAuth"
    ]
  }
};

export const groups = {
  "reddit": {
    "comments": "reddit-comments",
    "domainPosts": "reddit-domain-posts",
    "leads": "reddit-leads",
    "post": "reddit-post",
    "search": "reddit-search",
    "subredditAbout": "reddit-subreddit-about",
    "subredditComments": "reddit-subreddit-comments",
    "subredditPosts": "reddit-subreddit-posts",
    "subredditsPosts": "reddit-subreddits-posts",
    "trends": "reddit-trends",
    "userComments": "reddit-user-comments",
    "userPosts": "reddit-user-posts"
  }
};

export const operationCount = 12;

export const OperationIds = Object.freeze({
  "RedditComments": "reddit-comments",
  "RedditDomainPosts": "reddit-domain-posts",
  "RedditLeads": "reddit-leads",
  "RedditPost": "reddit-post",
  "RedditSearch": "reddit-search",
  "RedditSubredditAbout": "reddit-subreddit-about",
  "RedditSubredditComments": "reddit-subreddit-comments",
  "RedditSubredditPosts": "reddit-subreddit-posts",
  "RedditSubredditsPosts": "reddit-subreddits-posts",
  "RedditTrends": "reddit-trends",
  "RedditUserComments": "reddit-user-comments",
  "RedditUserPosts": "reddit-user-posts"
});
