// Generated by scripts/generate.py. Do not edit manually.

export type CrawloraResponse<T = unknown> = T;
export type CrawloraBody<T = Record<string, unknown>> = T;

export interface ModelAppResponse {
  "code"?: number;
  "data"?: unknown;
  "msg"?: unknown;
}

export interface ModelRedditUserPostsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditUserPostsResponse;
  "msg"?: string;
}

export interface ModelRedditUserPostsResponse {
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "source"?: ModelRedditSourceDetail;
  "username"?: string;
}

export interface ModelRedditSourceDetail {
  "type"?: string;
  "url"?: string;
}

export interface ModelRedditPost {
  "author"?: ModelRedditAuthor;
  "award_count"?: number;
  "comment_count"?: number;
  "created"?: string;
  "created_utc"?: number;
  "domain"?: string;
  "estimated_downvotes"?: number;
  "estimated_upvotes"?: number;
  "flair"?: string;
  "id"?: string;
  "is_self"?: boolean;
  "is_video"?: boolean;
  "locked"?: boolean;
  "name"?: string;
  "over_18"?: boolean;
  "permalink"?: string;
  "score"?: number;
  "selftext"?: string;
  "source_feed_url"?: string;
  "stickied"?: boolean;
  "subreddit"?: string;
  "thumbnail"?: string;
  "title"?: string;
  "upvote_ratio"?: number;
  "url"?: string;
  "vote_counts_estimated"?: boolean;
}

export interface ModelRedditAuthor {
  "name"?: string;
  "profile_url"?: string;
}

export interface ModelRedditPagination {
  "after"?: string;
  "limit"?: number;
}

export interface ModelRedditUserCommentsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditUserCommentsResponse;
  "msg"?: string;
}

export interface ModelRedditUserCommentsResponse {
  "comments"?: Array<ModelRedditComment>;
  "pagination"?: ModelRedditPagination;
  "source"?: ModelRedditSourceDetail;
  "username"?: string;
}

export interface ModelRedditComment {
  "author"?: ModelRedditAuthor;
  "award_count"?: number;
  "body"?: string;
  "created"?: string;
  "created_utc"?: number;
  "depth"?: number;
  "id"?: string;
  "name"?: string;
  "parent_id"?: string;
  "permalink"?: string;
  "replies"?: Array<ModelRedditComment>;
  "score"?: number;
}

export interface ModelRedditTrendsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditTrendsResponse;
  "msg"?: string;
}

export interface ModelRedditTrendsResponse {
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "sort"?: string;
  "source"?: ModelRedditSourceDetail;
  "time"?: string;
}

export interface ModelRedditMultiSubredditPostsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditMultiSubredditPostsResponse;
  "msg"?: string;
}

export interface ModelRedditMultiSubredditPostsResponse {
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "sort"?: string;
  "source"?: ModelRedditSourceDetail;
  "subreddits"?: Array<string>;
  "time"?: string;
}

export interface ModelRedditSubredditPostsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditSubredditPostsResponse;
  "msg"?: string;
}

export interface ModelRedditSubredditPostsResponse {
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "sort"?: string;
  "source"?: ModelRedditSourceDetail;
  "subreddit"?: string;
  "time"?: string;
}

export interface ModelRedditSubredditCommentsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditSubredditCommentsResponse;
  "msg"?: string;
}

export interface ModelRedditSubredditCommentsResponse {
  "comments"?: Array<ModelRedditComment>;
  "pagination"?: ModelRedditPagination;
  "source"?: ModelRedditSourceDetail;
  "subreddit"?: string;
}

export interface ModelRedditSubredditAboutResponseDoc {
  "code"?: number;
  "data"?: ModelRedditSubredditAboutResponse;
  "msg"?: string;
}

export interface ModelRedditSubredditAboutResponse {
  "display_name"?: string;
  "feed_url"?: string;
  "latest_post_created"?: string;
  "latest_post_created_utc"?: number;
  "public_url"?: string;
  "recent_post_count"?: number;
  "sample_posts"?: Array<ModelRedditPost>;
  "source"?: ModelRedditSourceDetail;
  "subreddit"?: string;
  "title"?: string;
}

export interface ModelRedditSearchResponseDoc {
  "code"?: number;
  "data"?: ModelRedditSearchResponse;
  "msg"?: string;
}

export interface ModelRedditSearchResponse {
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "query"?: string;
  "sort"?: string;
  "source"?: ModelRedditSourceDetail;
  "subreddit"?: string;
  "time"?: string;
}

export interface ModelRedditPostResponseDoc {
  "code"?: number;
  "data"?: ModelRedditPostResponse;
  "msg"?: string;
}

export interface ModelRedditPostResponse {
  "metrics_source"?: ModelRedditSourceDetail;
  "post"?: ModelRedditPost;
  "source"?: ModelRedditSourceDetail;
}

export interface ModelRedditLeadsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditleadsResponse;
  "msg"?: string;
}

export interface ModelRedditleadsResponse {
  "classifier"?: string;
  "degraded"?: boolean;
  "leads"?: Array<ModelRedditleadsLead>;
  "min_score"?: number;
  "model"?: string;
  "query"?: string;
  "stats"?: ModelRedditleadsStats;
  "subreddit"?: string;
}

export interface ModelRedditleadsStats {
  "classified"?: number;
  "prefiltered"?: number;
  "returned"?: number;
  "scanned"?: number;
}

export interface ModelRedditleadsLead {
  "author"?: string;
  "comment_count"?: number;
  "created"?: string;
  "permalink"?: string;
  "post_score"?: number;
  "reason"?: string;
  "score"?: number;
  "signals"?: Array<ModelRedditleadsSignal>;
  "subreddit"?: string;
  "title"?: string;
}

export interface ModelRedditleadsSignal {
  "id"?: string;
  "label"?: string;
}

export interface ModelRedditDomainPostsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditDomainPostsResponse;
  "msg"?: string;
}

export interface ModelRedditDomainPostsResponse {
  "domain"?: string;
  "pagination"?: ModelRedditPagination;
  "posts"?: Array<ModelRedditPost>;
  "sort"?: string;
  "source"?: ModelRedditSourceDetail;
  "time"?: string;
}

export interface ModelRedditCommentsResponseDoc {
  "code"?: number;
  "data"?: ModelRedditCommentsResponse;
  "msg"?: string;
}

export interface ModelRedditCommentsResponse {
  "comments"?: Array<ModelRedditComment>;
  "metrics_source"?: ModelRedditSourceDetail;
  "post"?: ModelRedditPost;
  "source"?: ModelRedditSourceDetail;
}

export type RedditCommentsResponse = CrawloraResponse<ModelRedditCommentsResponseDoc>;
export interface RedditCommentsParams {
  "id": string;
  "sort"?: "confidence" | "top" | "new" | "controversial" | "old" | "qa";
  "limit"?: number;
  "depth"?: number;
  "include_metrics"?: boolean;
}

export type RedditDomainPostsResponse = CrawloraResponse<ModelRedditDomainPostsResponseDoc>;
export interface RedditDomainPostsParams {
  "domain": string;
  "sort"?: "hot" | "new" | "top" | "rising";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "after"?: string;
}

export type RedditLeadsResponse = CrawloraResponse<ModelRedditLeadsResponseDoc>;
export interface RedditLeadsParams {
  "q": string;
  "subreddit"?: string;
  "sort"?: "relevance" | "hot" | "new" | "top" | "comments";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "min_score"?: number;
  "classifier"?: "auto" | "heuristic" | "llm";
}

export type RedditPostResponse = CrawloraResponse<ModelRedditPostResponseDoc>;
export interface RedditPostParams {
  "id": string;
  "include_metrics"?: boolean;
}

export type RedditSearchResponse = CrawloraResponse<ModelRedditSearchResponseDoc>;
export interface RedditSearchParams {
  "q": string;
  "subreddit"?: string;
  "sort"?: "relevance" | "hot" | "new" | "top" | "comments";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "after"?: string;
}

export type RedditSubredditAboutResponse = CrawloraResponse<ModelRedditSubredditAboutResponseDoc>;
export interface RedditSubredditAboutParams {
  "subreddit": string;
  "limit"?: number;
}

export type RedditSubredditCommentsResponse = CrawloraResponse<ModelRedditSubredditCommentsResponseDoc>;
export interface RedditSubredditCommentsParams {
  "subreddit": string;
  "limit"?: number;
  "after"?: string;
}

export type RedditSubredditPostsResponse = CrawloraResponse<ModelRedditSubredditPostsResponseDoc>;
export interface RedditSubredditPostsParams {
  "subreddit": string;
  "sort"?: "hot" | "new" | "top" | "rising";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "after"?: string;
}

export type RedditSubredditsPostsResponse = CrawloraResponse<ModelRedditMultiSubredditPostsResponseDoc>;
export interface RedditSubredditsPostsParams {
  "subreddits": string;
  "sort"?: "hot" | "new" | "top" | "rising";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "after"?: string;
}

export type RedditTrendsResponse = CrawloraResponse<ModelRedditTrendsResponseDoc>;
export interface RedditTrendsParams {
  "sort"?: "hot" | "new" | "rising" | "top";
  "time"?: "hour" | "day" | "week" | "month" | "year" | "all";
  "limit"?: number;
  "after"?: string;
}

export type RedditUserCommentsResponse = CrawloraResponse<ModelRedditUserCommentsResponseDoc>;
export interface RedditUserCommentsParams {
  "username": string;
  "limit"?: number;
  "after"?: string;
}

export type RedditUserPostsResponse = CrawloraResponse<ModelRedditUserPostsResponseDoc>;
export interface RedditUserPostsParams {
  "username": string;
  "limit"?: number;
  "after"?: string;
}

export interface RedditService {
  comments<T = RedditCommentsResponse>(params: RedditCommentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  domainPosts<T = RedditDomainPostsResponse>(params: RedditDomainPostsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  leads<T = RedditLeadsResponse>(params: RedditLeadsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  post<T = RedditPostResponse>(params: RedditPostParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  search<T = RedditSearchResponse>(params: RedditSearchParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  subredditAbout<T = RedditSubredditAboutResponse>(params: RedditSubredditAboutParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  subredditComments<T = RedditSubredditCommentsResponse>(params: RedditSubredditCommentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  subredditPosts<T = RedditSubredditPostsResponse>(params: RedditSubredditPostsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  subredditsPosts<T = RedditSubredditsPostsResponse>(params: RedditSubredditsPostsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  trends<T = RedditTrendsResponse>(params?: RedditTrendsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  userComments<T = RedditUserCommentsResponse>(params: RedditUserCommentsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
  userPosts<T = RedditUserPostsResponse>(params: RedditUserPostsParams, options?: import('./index.js').CrawloraRequestOptions): Promise<T>;
}

export interface CrawloraGeneratedGroups {
  reddit: RedditService;
}

export interface OperationParamsMap {
  "reddit-comments": RedditCommentsParams;
  "reddit-domain-posts": RedditDomainPostsParams;
  "reddit-leads": RedditLeadsParams;
  "reddit-post": RedditPostParams;
  "reddit-search": RedditSearchParams;
  "reddit-subreddit-about": RedditSubredditAboutParams;
  "reddit-subreddit-comments": RedditSubredditCommentsParams;
  "reddit-subreddit-posts": RedditSubredditPostsParams;
  "reddit-subreddits-posts": RedditSubredditsPostsParams;
  "reddit-trends": RedditTrendsParams;
  "reddit-user-comments": RedditUserCommentsParams;
  "reddit-user-posts": RedditUserPostsParams;
}

export interface OperationResponseMap {
  "reddit-comments": RedditCommentsResponse;
  "reddit-domain-posts": RedditDomainPostsResponse;
  "reddit-leads": RedditLeadsResponse;
  "reddit-post": RedditPostResponse;
  "reddit-search": RedditSearchResponse;
  "reddit-subreddit-about": RedditSubredditAboutResponse;
  "reddit-subreddit-comments": RedditSubredditCommentsResponse;
  "reddit-subreddit-posts": RedditSubredditPostsResponse;
  "reddit-subreddits-posts": RedditSubredditsPostsResponse;
  "reddit-trends": RedditTrendsResponse;
  "reddit-user-comments": RedditUserCommentsResponse;
  "reddit-user-posts": RedditUserPostsResponse;
}

export interface OperationRequiredParamsMap {
  "reddit-comments": true;
  "reddit-domain-posts": true;
  "reddit-leads": true;
  "reddit-post": true;
  "reddit-search": true;
  "reddit-subreddit-about": true;
  "reddit-subreddit-comments": true;
  "reddit-subreddit-posts": true;
  "reddit-subreddits-posts": true;
  "reddit-trends": false;
  "reddit-user-comments": true;
  "reddit-user-posts": true;
}

export type OperationId = keyof OperationParamsMap;

export type OperationRequestArgs<I extends OperationId> =
  OperationRequiredParamsMap[I] extends true
    ? [params: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions]
    : [params?: OperationParamsMap[I], options?: import('./index.js').CrawloraRequestOptions];

export type OperationIdLiteral =
  | "reddit-comments"
  | "reddit-domain-posts"
  | "reddit-leads"
  | "reddit-post"
  | "reddit-search"
  | "reddit-subreddit-about"
  | "reddit-subreddit-comments"
  | "reddit-subreddit-posts"
  | "reddit-subreddits-posts"
  | "reddit-trends"
  | "reddit-user-comments"
  | "reddit-user-posts";

export declare const OperationIds: Readonly<{
  RedditComments: "reddit-comments";
  RedditDomainPosts: "reddit-domain-posts";
  RedditLeads: "reddit-leads";
  RedditPost: "reddit-post";
  RedditSearch: "reddit-search";
  RedditSubredditAbout: "reddit-subreddit-about";
  RedditSubredditComments: "reddit-subreddit-comments";
  RedditSubredditPosts: "reddit-subreddit-posts";
  RedditSubredditsPosts: "reddit-subreddits-posts";
  RedditTrends: "reddit-trends";
  RedditUserComments: "reddit-user-comments";
  RedditUserPosts: "reddit-user-posts";
}>;
