// Code generated by the Crawlora platform SDK generator. DO NOT EDIT.

package reddit

import (
	"context"
	"sort"
)

type parameterDefinition struct {
	Name             string
	In               string
	Type             string
	CollectionFormat string
	Required         bool
	Enum             []string
}

type operationDefinition struct {
	Method      string
	Path        string
	PathParams  []string
	QueryParams []parameterDefinition
	Produces    []string
	Security    []string
}

var operations = map[string]operationDefinition{
	"reddit-comments":           operationDefinition{Method: "GET", Path: "/reddit/comments/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"confidence", "top", "new", "controversial", "old", "qa"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "depth", In: "query", Type: "integer"}, parameterDefinition{Name: "include_metrics", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-domain-posts":       operationDefinition{Method: "GET", Path: "/reddit/domain/{domain}/posts", PathParams: []string{"domain"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"hot", "new", "top", "rising"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-leads":              operationDefinition{Method: "GET", Path: "/reddit/leads", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "subreddit", In: "query", Type: "string"}, parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"relevance", "hot", "new", "top", "comments"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "min_score", In: "query", Type: "integer"}, parameterDefinition{Name: "classifier", In: "query", Type: "string", Enum: []string{"auto", "heuristic", "llm"}}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-post":               operationDefinition{Method: "GET", Path: "/reddit/post/{id}", PathParams: []string{"id"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "include_metrics", In: "query", Type: "boolean"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-search":             operationDefinition{Method: "GET", Path: "/reddit/search", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "q", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "subreddit", In: "query", Type: "string"}, parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"relevance", "hot", "new", "top", "comments"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-subreddit-about":    operationDefinition{Method: "GET", Path: "/reddit/subreddit/{subreddit}/about", PathParams: []string{"subreddit"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "limit", In: "query", Type: "integer"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-subreddit-comments": operationDefinition{Method: "GET", Path: "/reddit/subreddit/{subreddit}/comments", PathParams: []string{"subreddit"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-subreddit-posts":    operationDefinition{Method: "GET", Path: "/reddit/subreddit/{subreddit}/posts", PathParams: []string{"subreddit"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"hot", "new", "top", "rising"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-subreddits-posts":   operationDefinition{Method: "GET", Path: "/reddit/subreddits/posts", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "subreddits", In: "query", Type: "string", Required: true}, parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"hot", "new", "top", "rising"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-trends":             operationDefinition{Method: "GET", Path: "/reddit/trends", PathParams: nil, QueryParams: []parameterDefinition{parameterDefinition{Name: "sort", In: "query", Type: "string", Enum: []string{"hot", "new", "rising", "top"}}, parameterDefinition{Name: "time", In: "query", Type: "string", Enum: []string{"hour", "day", "week", "month", "year", "all"}}, parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-user-comments":      operationDefinition{Method: "GET", Path: "/reddit/user/{username}/comments", PathParams: []string{"username"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
	"reddit-user-posts":         operationDefinition{Method: "GET", Path: "/reddit/user/{username}/posts", PathParams: []string{"username"}, QueryParams: []parameterDefinition{parameterDefinition{Name: "limit", In: "query", Type: "integer"}, parameterDefinition{Name: "after", In: "query", Type: "string"}}, Produces: []string{"application/json"}, Security: []string{"ApiKeyAuth"}},
}

// OperationCount reports how many selected-platform operations this module exposes.
const OperationCount = 12

// OperationIDs returns the selected operation IDs in stable sorted order.
func OperationIDs() []string {
	ids := make([]string, 0, len(operations))
	for id := range operations {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	return ids
}

// Comments calls the reddit-comments operation.
func (c *Client) Comments(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-comments", params)
}

// DomainPosts calls the reddit-domain-posts operation.
func (c *Client) DomainPosts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-domain-posts", params)
}

// Leads calls the reddit-leads operation.
func (c *Client) Leads(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-leads", params)
}

// Post calls the reddit-post operation.
func (c *Client) Post(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-post", params)
}

// Search calls the reddit-search operation.
func (c *Client) Search(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-search", params)
}

// SubredditAbout calls the reddit-subreddit-about operation.
func (c *Client) SubredditAbout(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-subreddit-about", params)
}

// SubredditComments calls the reddit-subreddit-comments operation.
func (c *Client) SubredditComments(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-subreddit-comments", params)
}

// SubredditPosts calls the reddit-subreddit-posts operation.
func (c *Client) SubredditPosts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-subreddit-posts", params)
}

// SubredditsPosts calls the reddit-subreddits-posts operation.
func (c *Client) SubredditsPosts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-subreddits-posts", params)
}

// Trends calls the reddit-trends operation.
func (c *Client) Trends(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-trends", params)
}

// UserComments calls the reddit-user-comments operation.
func (c *Client) UserComments(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-user-comments", params)
}

// UserPosts calls the reddit-user-posts operation.
func (c *Client) UserPosts(ctx context.Context, params Params) (any, error) {
	return c.Call(ctx, "reddit-user-posts", params)
}
